# Generated by Django 6.0.4 on 2026-05-13 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "street_address1",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "street_address2",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "town_or_city",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("postcode", models.CharField(blank=True, max_length=20, null=True)),
                ("country", models.CharField(blank=True, max_length=40, null=True)),
                ("county", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
